const arr = [
    {
      name: 'Rounded Red Hat',
      smallImgs: [
        'small1.jpg',
        'small2.jpg',
        'small3.jpg',
        'small4.jpg',
        'small5.jpg',
        'small6.jpg',
        'small7.jpg',
        'small8.jpg',
        'small9.jpg',
      ],
      bigImgs: [
        'base1.jpg',
        'base2.jpg',
        'base3.jpg',
        'base4.jpg',
        'base5.jpg',
        'base6.jpg',
        'base7.jpg',
        'base8.jpg',
        'base9.jpg',
      ],
      price: 34,
      counts: 0,
      colors: [
        'rgb(255, 108, 108)',
        'rgb(255, 118, 41)',
        'rgb(255, 240, 108)',
        'rgb(108, 123, 255)',
        'rgb(138, 108, 255)',
      ],
      sizes: ['S', 'M', 'L'],
      tags: ['Fashion', 'Hats', 'Sandal', 'Belt', 'Bags'],
      brand: 'Retrolie',
      gender: 'male',
      collection: ['All products', 'Best sellers', 'Accessories'],
    },
    {
      name: 'Linen-blend Shirt',
      smallImgs: [
        'small1.jpg',
        'small2.jpg',
        'small3.jpg',
        'small4.jpg',
        'small5.jpg',
        'small6.jpg',
        'small7.jpg',
        'small8.jpg',
        'small9.jpg',
      ],
      bigImgs: [
        'base1.jpg',
        'base2.jpg',
        'base3.jpg',
        'base4.jpg',
        'base5.jpg',
        'base6.jpg',
        'base7.jpg',
        'base8.jpg',
        'base9.jpg',
      ],
      price: 34,
      oldprice: 45,
      counts: 15,
      colors: [
        'rgb(138, 108, 255)',
        'rgb(182, 108, 255)',
        'rgb(252, 108, 255)',
        'rgb(255, 108, 105)',
      ],
  
      sizes: ['XXL'],
      tags: ['Fashion', 'Hats', 'Sandal', 'Vagabond', 'Sunglasses', 'Beachwear'],
  
      brand: 'Brook',
      gender: 'male',
      collection: ['All products', 'Best sellers', 'New arrivals', 'Accessories'],
      discountTime: new Date('2024-11-12T12:00:00'),
    },
    {
      name: 'Long-sleeve Coat',
      smallImgs: [
        'small1.jpg',
        'small2.jpg',
        'small3.jpg',
        'small4.jpg',
        'small5.jpg',
        'small6.jpg',
        'small7.jpg',
        'small8.jpg',
        'small9.jpg',
      ],
      bigImgs: [
        'base1.jpg',
        'base2.jpg',
        'base3.jpg',
        'base4.jpg',
        'base5.jpg',
        'base6.jpg',
        'base7.jpg',
        'base8.jpg',
        'base9.jpg',
      ],
      price: 34,
      counts: 9,
      colors: [
        'rgb(108, 246, 255)',
        'rgb(108, 167, 255)',
        'rgb(108, 123, 255)',
        'rgb(138, 108, 255)',
        'rgb(182, 108, 255)',
      ],
  
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      tags: [
        'Fashion',
        'Hats',
        'Denim',
        'Minimog',
        'Vagabond',
        'Sunglasses',
        'Beachwear',
      ],
  
      brand: 'Learts',
      gender: 'male',
      collection: ['All products', 'Accessories'],
      
    },
    {
      name: 'Boxy Denim Hat',
      smallImgs: [
        'small1.jpg',
        'small2.jpg',
        'small3.jpg',
        'small4.jpg',
        'small5.jpg',
        'small6.jpg',
        'small7.jpg',
        'small8.jpg',
        'small9.jpg',
      ],
      bigImgs: [
        'base1.jpg',
        'base2.jpg',
        'base3.jpg',
        'base4.jpg',
        'base5.jpg',
        'base6.jpg',
        'base7.jpg',
        'base8.jpg',
        'base9.jpg',
      ],
      price: 60,
      counts: 25,
      colors: [
        'rgb(255, 108, 108)',
        'rgb(255, 118, 41)',
        'rgb(252, 108, 255)',
        'rgb(255, 108, 105)',
      ],
  
      sizes: ['S', 'M', 'XXL'],
      tags: [
        'Sandal',
        'Belt',
        'Bags',
        'Snacker',
        'Denim',
        'Minimog',
        'Vagabond',
        'Sunglasses',
        'Beachwear',
      ],
  
      brand: 'Abby',
      gender: 'male',
      collection: ['All products', 'Best sellers', 'New arrivals', 'Accessories'],
    },
    {
      name: 'Linen Plain Top',
      smallImgs: [
        'small1.jpg',
        'small2.jpg',
        'small3.jpg',
        'small4.jpg',
        'small5.jpg',
        'small6.jpg',
        'small7.jpg',
        'small8.jpg',
        'small9.jpg',
      ],
      bigImgs: [
        'base1.jpg',
        'base2.jpg',
        'base3.jpg',
        'base4.jpg',
        'base5.jpg',
        'base6.jpg',
        'base7.jpg',
        'base8.jpg',
        'base9.jpg',
      ],
      price: 150,
      oldprice: 240,
      counts: 6,
      colors: [
        'rgb(108, 246, 255)',
        'rgb(108, 167, 255)',
        'rgb(108, 123, 255)',
        'rgb(138, 108, 255)',
        'rgb(182, 108, 255)',
        'rgb(252, 108, 255)',
        'rgb(255, 108, 105)',
      ],
  
      sizes: ['S'],
      tags: ['Fashion', 'Hats', 'Sandal', 'Belt', 'Bags'],
  
      brand: 'Learts',
      gender: 'male',
      collection: ['All products', 'Accessories'],
      discountTime: new Date('2024-12-12T12:00:00'),
    },
    {
      name: 'Oversized T-shirt',
      smallImgs: [
        'small1.jpg',
        'small2.jpg',
        'small3.jpg',
        'small4.jpg',
        'small5.jpg',
        'small6.jpg',
        'small7.jpg',
        'small8.jpg',
        'small9.jpg',
      ],
      bigImgs: [
        'base1.jpg',
        'base2.jpg',
        'base3.jpg',
        'base4.jpg',
        'base5.jpg',
        'base6.jpg',
        'base7.jpg',
        'base8.jpg',
        'base9.jpg',
      ],
      price: 105,
      counts: 9,
      colors: [
        'rgb(108, 246, 255)',
        'rgb(108, 167, 255)',
        'rgb(108, 123, 255)',
        'rgb(138, 108, 255)',
        'rgb(182, 108, 255)',
        'rgb(252, 108, 255)',
        'rgb(255, 108, 105)',
      ],
  
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      tags: ['Denim', 'Minimog', 'Vagabond', 'Sunglasses', 'Beachwear'],
  
      brand: 'Retrolie',
      gender: 'male',
      collection: ['All products', 'New arrivals', 'Accessories'],
    },
    {
      name: 'Polarised Sunglasses',
      smallImgs: [
        'small1.jpg',
        'small2.jpg',
        'small3.jpg',
        'small4.jpg',
        'small5.jpg',
        'small6.jpg',
        'small7.jpg',
        'small8.jpg',
        'small9.jpg',
      ],
      bigImgs: [
        'base1.jpg',
        'base2.jpg',
        'base3.jpg',
        'base4.jpg',
        'base5.jpg',
        'base6.jpg',
        'base7.jpg',
        'base8.jpg',
        'base9.jpg',
      ],
      price: 15,
      oldprice: 25,
      counts: 8,
      colors: ['rgb(182, 108, 255)', 'rgb(252, 108, 255)', 'rgb(255, 108, 105)'],
  
      sizes: ['S', 'M'],
      tags: ['Fashion', 'Sunglasses'],
  
      brand: 'Brook',
      gender: 'male',
      collection: ['All products', 'Best sellers', 'Accessories'],
      discountTime: new Date('2024-11-18T12:00:00'),
    },
    {
      name: 'Rockstar Jacket',
      smallImgs: [
        'small1.jpg',
        'small2.jpg',
        'small3.jpg',
        'small4.jpg',
        'small5.jpg',
        'small6.jpg',
        'small7.jpg',
        'small8.jpg',
        'small9.jpg',
      ],
      bigImgs: [
        'base1.jpg',
        'base2.jpg',
        'base3.jpg',
        'base4.jpg',
        'base5.jpg',
        'base6.jpg',
        'base7.jpg',
        'base8.jpg',
        'base9.jpg',
      ],
      price: 34,
      oldprice: 45,
      counts: 15,
      colors: ['rgb(108, 167, 255)', 'rgb(108, 123, 255)', 'rgb(138, 108, 255)'],
  
      sizes: ['S', 'M', 'L', 'XXL'],
      tags: ['Denim', 'Minimog', 'Vagabond', 'Beachwear'],
  
      brand: 'Learts',
      gender: 'male',
      collection: ['All products', 'Best sellers', 'New arrivals'],
      discountTime: new Date('2024-11-12T12:00:00'),
    },
    {
      name: 'Dotted Black Dress',
      smallImgs: [
        'small1.jpg',
        'small2.jpg',
        'small3.jpg',
        'small4.jpg',
        'small5.jpg',
        'small6.jpg',
        'small7.jpg',
        'small8.jpg',
        'small9.jpg',
      ],
      bigImgs: [
        'base1.jpg',
        'base2.jpg',
        'base3.jpg',
        'base4.jpg',
        'base5.jpg',
        'base6.jpg',
        'base7.jpg',
        'base8.jpg',
        'base9.jpg',
      ],
      price: 150,
      oldprice: 180,
      counts: 13,
      colors: [
        'rgb(255, 108, 108)',
        'rgb(255, 118, 41)',
        'rgb(255, 240, 108)',
        'rgb(155, 255, 108)',
        'rgb(108, 185, 255)',
        'rgb(108, 246, 255)',
        'rgb(108, 167, 255)',
        'rgb(108, 123, 255)',
        'rgb(138, 108, 255)',
      ],
  
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      tags: [
        'Fashion',
        'Bags',
        'Snacker',
        'Denim',
        'Minimog',
        'Vagabond',
        'Beachwear',
      ],
  
      brand: 'Vagabond',
      gender: 'male',
      collection: ['All products', 'Best sellers'],
      discountTime: new Date('2024-11-18T12:00:00'),
    },
    {
      name: 'Rounded Red Hat2',
      smallImgs: [
        'small1.jpg',
        'small2.jpg',
        'small3.jpg',
        'small4.jpg',
        'small5.jpg',
        'small6.jpg',
        'small7.jpg',
        'small8.jpg',
        'small9.jpg',
      ],
      bigImgs: [
        'base1.jpg',
        'base2.jpg',
        'base3.jpg',
        'base4.jpg',
        'base5.jpg',
        'base6.jpg',
        'base7.jpg',
        'base8.jpg',
        'base9.jpg',
      ],
      price: 34,
      counts: 0,
      colors: [
        'rgb(255, 108, 108)',
        'rgb(255, 118, 41)',
        'rgb(255, 240, 108)',
        'rgb(108, 123, 255)',
        'rgb(138, 108, 255)',
      ],
      sizes: ['S', 'M', 'L'],
      tags: ['Fashion', 'Hats', 'Sandal', 'Belt', 'Bags'],
      brand: 'Retrolie',
      gender: 'male',
      collection: ['All products', 'Best sellers', 'Accessories'],
    },
    {
      name: 'Linen-blend Shirt2',
      smallImgs: [
        'small1.jpg',
        'small2.jpg',
        'small3.jpg',
        'small4.jpg',
        'small5.jpg',
        'small6.jpg',
        'small7.jpg',
        'small8.jpg',
        'small9.jpg',
      ],
      bigImgs: [
        'base1.jpg',
        'base2.jpg',
        'base3.jpg',
        'base4.jpg',
        'base5.jpg',
        'base6.jpg',
        'base7.jpg',
        'base8.jpg',
        'base9.jpg',
      ],
      price: 34,
      oldprice: 45,
      counts: 15,
      colors: [
        'rgb(138, 108, 255)',
        'rgb(182, 108, 255)',
        'rgb(252, 108, 255)',
        'rgb(255, 108, 105)',
      ],
  
      sizes: ['XXL'],
      tags: ['Fashion', 'Hats', 'Sandal', 'Vagabond', 'Sunglasses', 'Beachwear'],
  
      brand: 'Brook',
      gender: 'male',
      collection: ['All products', 'Best sellers', 'New arrivals', 'Accessories'],
      discountTime: new Date('2024-11-12T12:00:00'),
    },
    {
      name: 'Long-sleeve Coat2',
      smallImgs: [
        'small1.jpg',
        'small2.jpg',
        'small3.jpg',
        'small4.jpg',
        'small5.jpg',
        'small6.jpg',
        'small7.jpg',
        'small8.jpg',
        'small9.jpg',
      ],
      bigImgs: [
        'base1.jpg',
        'base2.jpg',
        'base3.jpg',
        'base4.jpg',
        'base5.jpg',
        'base6.jpg',
        'base7.jpg',
        'base8.jpg',
        'base9.jpg',
      ],
      price: 34,
      oldprice: 45,
      counts: 9,
      colors: [
        'rgb(108, 246, 255)',
        'rgb(108, 167, 255)',
        'rgb(108, 123, 255)',
        'rgb(138, 108, 255)',
        'rgb(182, 108, 255)',
      ],
  
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      tags: [
        'Fashion',
        'Hats',
        'Denim',
        'Minimog',
        'Vagabond',
        'Sunglasses',
        'Beachwear',
      ],
  
      brand: 'Learts',
      gender: 'male',
      collection: ['All products', 'Accessories'],
      discountTime: new Date('2024-11-15T12:00:00'),
    },
    {
      name: 'Boxy Denim Hat2',
      smallImgs: [
        'small1.jpg',
        'small2.jpg',
        'small3.jpg',
        'small4.jpg',
        'small5.jpg',
        'small6.jpg',
        'small7.jpg',
        'small8.jpg',
        'small9.jpg',
      ],
      bigImgs: [
        'base1.jpg',
        'base2.jpg',
        'base3.jpg',
        'base4.jpg',
        'base5.jpg',
        'base6.jpg',
        'base7.jpg',
        'base8.jpg',
        'base9.jpg',
      ],
      price: 60,
      counts: 25,
      colors: [
        'rgb(255, 108, 108)',
        'rgb(255, 118, 41)',
        'rgb(252, 108, 255)',
        'rgb(255, 108, 105)',
      ],
  
      sizes: ['S', 'M', 'XXL'],
      tags: [
        'Sandal',
        'Belt',
        'Bags',
        'Snacker',
        'Denim',
        'Minimog',
        'Vagabond',
        'Sunglasses',
        'Beachwear',
      ],
  
      brand: 'Abby',
      gender: 'male',
      collection: ['All products', 'Best sellers', 'New arrivals', 'Accessories'],
    },
    {
      name: 'Linen Plain Top2',
      smallImgs: [
        'small1.jpg',
        'small2.jpg',
        'small3.jpg',
        'small4.jpg',
        'small5.jpg',
        'small6.jpg',
        'small7.jpg',
        'small8.jpg',
        'small9.jpg',
      ],
      bigImgs: [
        'base1.jpg',
        'base2.jpg',
        'base3.jpg',
        'base4.jpg',
        'base5.jpg',
        'base6.jpg',
        'base7.jpg',
        'base8.jpg',
        'base9.jpg',
      ],
      price: 150,
      oldprice: 240,
      counts: 6,
      colors: [
        'rgb(108, 246, 255)',
        'rgb(108, 167, 255)',
        'rgb(108, 123, 255)',
        'rgb(138, 108, 255)',
        'rgb(182, 108, 255)',
        'rgb(252, 108, 255)',
        'rgb(255, 108, 105)',
      ],
  
      sizes: ['S'],
      tags: ['Fashion', 'Hats', 'Sandal', 'Belt', 'Bags'],
  
      brand: 'Learts',
      gender: 'male',
      collection: ['All products', 'Accessories'],
      discountTime: new Date('2024-12-12T12:00:00'),
    },
    {
      name: 'Oversized T-shirt2',
      smallImgs: [
        'small1.jpg',
        'small2.jpg',
        'small3.jpg',
        'small4.jpg',
        'small5.jpg',
        'small6.jpg',
        'small7.jpg',
        'small8.jpg',
        'small9.jpg',
      ],
      bigImgs: [
        'base1.jpg',
        'base2.jpg',
        'base3.jpg',
        'base4.jpg',
        'base5.jpg',
        'base6.jpg',
        'base7.jpg',
        'base8.jpg',
        'base9.jpg',
      ],
      price: 105,
      counts: 9,
      colors: [
        'rgb(108, 246, 255)',
        'rgb(108, 167, 255)',
        'rgb(108, 123, 255)',
        'rgb(138, 108, 255)',
        'rgb(182, 108, 255)',
        'rgb(252, 108, 255)',
        'rgb(255, 108, 105)',
      ],
  
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      tags: ['Denim', 'Minimog', 'Vagabond', 'Sunglasses', 'Beachwear'],
  
      brand: 'Retrolie',
      gender: 'male',
      collection: ['All products', 'New arrivals', 'Accessories'],
    },
    {
      name: 'Polarised Sunglasses2',
      smallImgs: [
        'small1.jpg',
        'small2.jpg',
        'small3.jpg',
        'small4.jpg',
        'small5.jpg',
        'small6.jpg',
        'small7.jpg',
        'small8.jpg',
        'small9.jpg',
      ],
      bigImgs: [
        'base1.jpg',
        'base2.jpg',
        'base3.jpg',
        'base4.jpg',
        'base5.jpg',
        'base6.jpg',
        'base7.jpg',
        'base8.jpg',
        'base9.jpg',
      ],
      price: 15,
      oldprice: 25,
      counts: 8,
      colors: ['rgb(182, 108, 255)', 'rgb(252, 108, 255)', 'rgb(255, 108, 105)'],
  
      sizes: ['S', 'M'],
      tags: ['Fashion', 'Sunglasses'],
  
      brand: 'Brook',
      gender: 'male',
      collection: ['All products', 'Best sellers', 'Accessories'],
      discountTime: new Date('2024-11-18T12:00:00'),
    },
    {
      name: 'Rockstar Jacket2',
      smallImgs: [
        'small1.jpg',
        'small2.jpg',
        'small3.jpg',
        'small4.jpg',
        'small5.jpg',
        'small6.jpg',
        'small7.jpg',
        'small8.jpg',
        'small9.jpg',
      ],
      bigImgs: [
        'base1.jpg',
        'base2.jpg',
        'base3.jpg',
        'base4.jpg',
        'base5.jpg',
        'base6.jpg',
        'base7.jpg',
        'base8.jpg',
        'base9.jpg',
      ],
      price: 34,
      oldprice: 45,
      counts: 15,
      colors: ['rgb(108, 167, 255)', 'rgb(108, 123, 255)', 'rgb(138, 108, 255)'],
  
      sizes: ['S', 'M', 'L', 'XXL'],
      tags: ['Denim', 'Minimog', 'Vagabond', 'Beachwear'],
  
      brand: 'Learts',
      gender: 'male',
      collection: ['All products', 'Best sellers', 'New arrivals'],
      discountTime: new Date('2024-11-12T12:00:00'),
    },
    {
      name: 'Dotted Black Dress2',
      smallImgs: [
        'small1.jpg',
        'small2.jpg',
        'small3.jpg',
        'small4.jpg',
        'small5.jpg',
        'small6.jpg',
        'small7.jpg',
        'small8.jpg',
        'small9.jpg',
      ],
      bigImgs: [
        'base1.jpg',
        'base2.jpg',
        'base3.jpg',
        'base4.jpg',
        'base5.jpg',
        'base6.jpg',
        'base7.jpg',
        'base8.jpg',
        'base9.jpg',
      ],
      price: 150,
      oldprice: 180,
      counts: 13,
      colors: [
        'rgb(255, 108, 108)',
        'rgb(255, 118, 41)',
        'rgb(255, 240, 108)',
        'rgb(155, 255, 108)',
        'rgb(108, 185, 255)',
        'rgb(108, 246, 255)',
        'rgb(108, 167, 255)',
        'rgb(108, 123, 255)',
        'rgb(138, 108, 255)',
      ],
  
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      tags: [
        'Fashion',
        'Bags',
        'Snacker',
        'Denim',
        'Minimog',
        'Vagabond',
        'Beachwear',
      ],
  
      brand: 'Vagabond',
      gender: 'male',
      collection: ['All products', 'Best sellers'],
      discountTime: new Date('2024-11-18T12:00:00'),
    },
  ];